services:
  homebox:
    image: ghcr.io/hay-kot/homebox:latest
    environment:
      - HBOX_LOG_LEVEL=info
      - HBOX_LOG_FORMAT=text
      - HBOX_WEB_MAX_UPLOAD_SIZE=10
      - HBOX_OPTIONS_ALLOW_REGISTRATION=true
    ports:
      - 7745:7745

  homebox-ui:
    build:
      context: .
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./next.config.js:/app/next.config.js
      - ./next-env.d.ts:/app/next-env.d.ts
      - ./postcss.config.js:/app/postcss.config.js
      - ./tailwind.config.ts:/app/tailwind.config.ts
      - ./tsconfig.json:/app/tsconfig.json
