on: "push"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Editor Config
        uses: zbeekman/EditorConfig-Action@v1.1.1
